"use client";
import { motion } from "framer-motion";
import { BarChart3, BrainCircuit, BriefcaseBusiness, Database, Fingerprint, Network } from "lucide-react";

const features = [
  { icon: Database, title: "Profil talenta terintegrasi", text: "Menyatukan informasi personel, rekam kompetensi, pengalaman, dan hasil asesmen dalam satu profil talenta." },
  { icon: BrainCircuit, title: "Pemetaan berbasis kompetensi", text: "Menggambarkan kekuatan, potensi, serta area pengembangan personel secara terstruktur dan terukur." },
  { icon: BriefcaseBusiness, title: "Arah penempatan yang relevan", text: "Menyajikan informasi pendukung untuk menyelaraskan kapasitas personel dengan karakteristik penugasan." },
  { icon: BarChart3, title: "Dasbor pengambilan keputusan", text: "Memudahkan pimpinan membaca sebaran talenta dan kebutuhan pengembangan secara ringkas." },
];
export default function AboutSection() {
  return <><section id="tentang" className="bg-white py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-8">
    <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><p className="section-kicker">Tentang SIPETA POLRI</p><h2 className="section-title mt-5">Talenta personel terlihat. Arah pengembangan lebih terukur.</h2><p className="mt-7 text-lg leading-8 text-slate-600">SIPETA POLRI adalah sistem informasi yang membantu proses identifikasi, pemetaan, dan pengelolaan talenta personel Polri. Informasi disajikan sebagai bahan pendukung pembinaan karier, pengembangan kompetensi, dan penempatan yang selaras dengan kebutuhan organisasi.</p><div className="mt-9 rounded-2xl border-l-4 border-amber-400 bg-[#f5f7f9] p-6"><p className="font-bold text-[#0b2744]">Bukan sekadar hasil asesmen.</p><p className="mt-2 leading-7 text-slate-600">SIPETA membangun gambaran talenta yang utuh—siapa personelnya, apa kekuatannya, dan di area mana kapasitasnya dapat memberi kontribusi terbaik.</p></div></motion.div>
    <div className="grid gap-5 sm:grid-cols-2">{features.map(({icon:Icon,title,text}, i) => <motion.article key={title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{delay:i*.08}} viewport={{once:true}} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-[0_14px_45px_rgba(15,23,42,.06)]"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl bg-[#0b2744] text-amber-300"><Icon size={23}/></div><h3 className="text-xl font-bold text-[#0b2744]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></motion.article>)}</div>
  </div></section><section id="manfaat" className="bg-[#0b2744] py-20 text-white"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="section-kicker text-amber-300">Nilai Strategis</p><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Satu peta talenta, tiga arah keputusan.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[{icon:Fingerprint,n:"01",t:"Kenali",d:"Identifikasi profil dan kekuatan personel."},{icon:Network,n:"02",t:"Kembangkan",d:"Susun prioritas pengembangan kompetensi."},{icon:BriefcaseBusiness,n:"03",t:"Tempatkan",d:"Selaraskan talenta dengan kebutuhan peran."}].map(({icon:Icon,n,t,d})=><div key={n} className="rounded-2xl border border-white/10 bg-white/5 p-6"><div className="flex items-center justify-between"><Icon className="text-amber-300"/><span className="text-xs font-bold text-slate-500">{n}</span></div><h3 className="mt-8 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{d}</p></div>)}</div></div></div></section></>;
}
